---
- name: Configure Password History Policy Correctly in Amazon Linux 2023
  hosts: all
  become: true  # Run as root
  tasks:
    - name: Ensure pam_pwhistory.so is correctly positioned in /etc/pam.d/system-auth
      lineinfile:
        path: /etc/pam.d/system-auth
        insertafter: "^password\\s+requisite\\s+pam_pwquality.so.*"
        line: "password    required      pam_pwhistory.so remember=24"
        state: present
        backup: yes

    - name: Ensure pam_pwhistory.so is correctly positioned in /etc/pam.d/password-auth
      lineinfile:
        path: /etc/pam.d/password-auth
        insertafter: "^password\\s+requisite\\s+pam_pwquality.so.*"
        line: "password    required      pam_pwhistory.so remember=24"
        state: present
        backup: yes

    - name: Verify changes in system-auth
      command: cat /etc/pam.d/system-auth
      register: system_auth_content
      changed_when: false

    - name: Display system-auth content
      debug:
        var: system_auth_content.stdout_lines

    - name: Verify changes in password-auth
      command: cat /etc/pam.d/password-auth
"password_policy.yml" 39L, 1285C
